### PR TITLE
Retry proxy

### PR DESCRIPTION
**Pull request by rowleya**
Adds a proxy that can be used to help with server restarts

### CODE REVIEW

**Comment by dkfellows** [comment]
I wonder whether the proxy code should be its own submodule.

**Comment by dkfellows** [comment]
Also, how is this code used? 😉

**Comment by rowleya** [comment]
At present, the servers are started with a non-normal compat port, and the proxy is then run against the real port connecting to this non-normal port (e.g. the proxy listens on 22244 and the server listens on 22254).  If we restart the server and leave the proxy running, the user will not be disconnected, and the should be able to continue using the software when the service resumes (normal restarts are quick enough that jobs won't expire).

**Comment by rowleya** [comment]
It isn't super critical, it was just to allow me to restart things when users are busy :)

**Comment by dkfellows** [comment]
So this will be something that gets deployed separately. Which means it needs to go in the deployment instructions, and probably should also be its own submodule (as it is its own tiny little artefact).

**Comment by dkfellows** [comment]
FWIW, I approve of the principle. I'm nitpicking.

**Comment by rowleya** [comment]
> So this will be something that gets deployed separately. Which means it needs to go in the deployment instructions, and probably should also be its own submodule (as it is its own tiny little artefact).

Yes to both those things; I will try to split it out

**Review by dkfellows — APPROVED** [review]

**Comment by dkfellows** [comment]
I suppose it ought to be writing to a logfile instead of stderr. Fixable later.

**Pull request merged**
