### PR TITLE
Java package structure

### PR DESCRIPTION
**Pull request by dkfellows**
Build out more of the metadata structure

The `RemoveMe` classes are just there to stop the javadoc build from blowing up, and should be deleted once we have real code in those packages.

### CODE REVIEW

**Comment by rowleya** [comment]
Just a note - spinnaker.manchester.ac.uk doesn't exist; spinnaker.cs.manchester.ac.uk does.

**Comment by rowleya** [comment]
Another note - is SpiNNaker-transceiver what you want as the name?  Would SpiNNaker-comms be better (agree that SpiNNMan probably doesn't say much).  Similarly, we could take this opportunity to make SpiNNaker-PACMAN into SpiNNaker-mapping?

**Comment by dkfellows** [comment]
Re the overall name (and whether it has `cs` in it), that's only important if another project or organisation in the university is called “spinnaker” _and_ code from there is used in the same process. Vanishingly unlikely. Otherwise it just adds noise.

**Comment by dkfellows** [comment]
Maven submodules can be renamed easily at this stage as we've not got lots of inter-module dependencies yet. If we know what they should be, I'll just change them.

**Pull request merged**
