### PR TITLE
Try to prevent catastrophes from occurring

### PR DESCRIPTION
**Pull request by dkfellows**
I suspect some sort of weird thread funkiness. Let's be careful...

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
Yes, full sync is a good idea!

**Comment by rowleya** [comment]
Worth an integration test, just to be sure?

**Comment by Christian-B** [comment]
> Worth an integration test, just to be sure?

Conisdering  branch dist_dep_weights_delays failed twice in the same way may be worth testing against that

**Comment by rowleya** [comment]
A branch has been made of this with the name dist_dep_weights_delays to test...

**Comment by dkfellows** [comment]
If you _can_ test this, please do. Threading-related issues are disgustingly difficult to test…

**Comment by rowleya** [comment]
It was more of a "does it fail on some odd test case now it has changed"; if all tests pass on that branch I think that can be called success, even if it wasn't actually because of this change!

**Pull request merged**
