### PR TITLE
Release 6.0.0

### PR DESCRIPTION
**Pull request by dkfellows**
This branch contains work on producing the 6.0 release. _**It will not be merged.**_ The PR is just for our operational convenience.

### CODE REVIEW

**Review by Christian-B — COMMENTED** [review]
Looks fine. Do not merge into master as with all 6.0.0 branches

**Comment by Christian-B** [comment]
This branch now contains updates that should not be lost after the release!

**Comment by dkfellows** [comment]
Things that should not be lost are in #287

**Comment by dkfellows** [comment]
Release done

**Pull request closed without merging**
