### PR TITLE
More javadoc finickiness

### PR DESCRIPTION
**Pull request by dkfellows**
This PR is a consequence of me using `mvn javadoc:aggregate` to find publishing issues and other annoying things like that.

We stop documenting `keycloak-management-client` because it was causing the oddest failures in doc builds and is really not something that users can use. (You have to edit the code to make changes at all; it's extremely non-general!)

### CODE REVIEW

**Comment by dkfellows** [comment]
In some cases, we "document" things by changing the visibility of some setters to package-private. If the class is definitely never meant to have those called except via Jackson (which can see behind the curtain) then it doesn't need to wave them around.

The change is large simply because it documents *all* those little getters. And I need to double check that everything used in the UI still has enough visibility because those are pseudo-scripted.

**Comment by rowleya** [comment]
I believe that Jackson can set private properties directly if you so wish i.e. no need for a setter...

**Comment by dkfellows** [comment]
Checks:

- [x] `SystemControllerImpl`
- [ ] `AdminControllerImpl`
- [ ] `RootController`

**Comment by dkfellows** [comment]
Looks OK. Or rather #560 isn't a bug with this branch.

**Pull request merged**
